var ages = [20, 14, 50, 40, 60];
// console.log(ages);
// ages.push(40);
// console.log(ages);
// ages.pop();
console.log(ages);
ages.pop();
console.log(ages);
// var elements=ages.pop();
// console.log(elements);
ages =[10, ...ages];
console.log(ages);